defaults:
  - _self_
  #- dataset: YBCO13
  #- dataset: lim_l6
  #- dataset: ICSG3D
  # paper_version_datasets
  #- dataset: YBCO13_paper
  - dataset: lim_l6_paper
  #- dataset: ICSG3D_paper
  #- network: nesf
  - network: nesf_pe

data_module:
  #batch_size: 128
  batch_size: 64
  num_dataloder_workers: 4

sampling:
  training:
    global:
      interval: 1.0 #Angstrom
      stddev: 0.5 #Angstrom
    local:
      interval: 0.3 #Angstrom
      range: 1.2 #Angstrom
      stddev: 0.15 #Angstrom
    species:
      interval: 0.1 #Angstrom
      range: 0.6 #Angstrom
      stddev: 0.05 #Angstrom
  inference:
    global:
      interval: 0.5 #Angstrom
    species:
      interval: 0.1 #Angstrom
      range: 0.6 #Angstrom

loss_weights:
  pos: 10.0
  spec: 0.1
  length: 1.0
  angle: 1.0
  kld: 0.001

training:
  lr: 0.001
  scheduler_step_size: 640
  scheduler_gamma: 0.5

trainer:
  #max_epochs: 3200
  max_epochs: 1

logger:
  project: NeSF_project
  name: NeSF
  save_dir: /workspace/logs
  #log_model: all # last and best weights are saved
  log_model: True # last and best weights are saved

checkpoint:
  monitor: "val_loss"
  save_top_k: 3
  mode: "min"
  save_last: True
  dirpath: "/workspace/checkpoints/" 

reconstruction:
  mode: trained # ground_truth or trained
  #mode: ground_truth # ground_truth or trained
  batch_size: 64
  num_iteration: 64
  residual_distance_threshold: 0.9
  nms:
    radius: 0.5
    num_points_threshold: 10
  output_dir: "/workspace/reconstruction/"

trained_checkpoints:
  ICSG3D_paper: "/workspace/checkpoints/NeSF_project/8wous5wy/last.ckpt"
  lim_l6_paper: "/workspace/checkpoints/NeSF_project/h903xnzj/last.ckpt"
  YBCO13_fold0_paper: "/workspace/checkpoints/NeSF_project/8e30t383/last.ckpt"
  YBCO13_fold1_paper: "/workspace/checkpoints/NeSF_project/r8fcogdq/last.ckpt"
  YBCO13_fold2_paper: "/workspace/checkpoints/NeSF_project/878rjniq/last.ckpt"
  YBCO13_fold3_paper: "/workspace/checkpoints/NeSF_project/xd4yujfu/last.ckpt"
  YBCO13_fold4_paper: "/workspace/checkpoints/NeSF_project/g3abimyt/last.ckpt"
  YBCO13_fold5_paper: "/workspace/checkpoints/NeSF_project/qsh77yes/last.ckpt"
  YBCO13_fold6_paper: "/workspace/checkpoints/NeSF_project/dalmn5ve/last.ckpt"
  YBCO13_fold7_paper: "/workspace/checkpoints/NeSF_project/b0dhdzc6/last.ckpt"
  YBCO13_fold8_paper: "/workspace/checkpoints/NeSF_project/dljazdez/last.ckpt"
  YBCO13_fold9_paper: "/workspace/checkpoints/NeSF_project/omme6nzg/last.ckpt"
  YBCO13_fold10_paper: "/workspace/checkpoints/NeSF_project/innhxihc/last.ckpt"
  YBCO13_fold11_paper: "/workspace/checkpoints/NeSF_project/zve5leed/last.ckpt"
  YBCO13_fold12_paper: "/workspace/checkpoints/NeSF_project/02cykqok/last.ckpt"
  YBCO13_fold13_paper: "/workspace/checkpoints/NeSF_project/d6q5mit9/last.ckpt"
  YBCO13_fold14_paper: "/workspace/checkpoints/NeSF_project/mjxap3zr/last.ckpt"
  YBCO13_fold15_paper: "/workspace/checkpoints/NeSF_project/qxwxun9l/last.ckpt"
  YBCO13_fold16_paper: "/workspace/checkpoints/NeSF_project/bmf06m6x/last.ckpt"
  YBCO13_fold17_paper: "/workspace/checkpoints/NeSF_project/pfxkeib1/last.ckpt"
  YBCO13_fold18_paper: "/workspace/checkpoints/NeSF_project/p2rixlg4/last.ckpt"
  YBCO13_fold19_paper: "/workspace/checkpoints/NeSF_project/2oyr8dl2/last.ckpt"

evaluate:
  log_dir: "/workspace/evaluation/"
