dataset_name: "ICSG3D_paper"
train_dataset_dir: "/workspace/data/dataset_paper/dataset_ICSG3D_train"
validation_dataset_dir: "/workspace/data/dataset_paper/dataset_ICSG3D_val"
test_dataset_dir: "/workspace/data/dataset_paper/dataset_ICSG3D_test"  
