dataset_name: "lim_l6"
train_dataset_dir: "/workspace/data/dataset_paper/dataset_lim_l6_train"
validation_dataset_dir: "/workspace/data/dataset_paper/dataset_lim_l6_val"
test_dataset_dir: "/workspace/data/dataset_paper/dataset_lim_l6_test"  
