dataset_name: "YBCO13_fold13"
    train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold13_train"
    validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold13_val"
    test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold13_test"  
    