dataset_name: "YBCO13_fold0"
    train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold0_train"
    validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold0_val"
    test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold0_test"  
    