dataset_name: "YBCO13_fold14"
train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold14_train"
validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold14_val"
test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold14_test"  
