dataset_name: "YBCO13_fold12"
    train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold12_train"
    validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold12_val"
    test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold12_test"  
    