dataset_name: "YBCO13_fold4"
train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold4_train"
validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold4_val"
test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold4_test"  
