dataset_name: "YBCO13_fold3"
    train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold3_train"
    validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold3_val"
    test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold3_test"  
    