dataset_name: "YBCO13_fold9_paper"
train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold9_train"
validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold9_val"
test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold9_test"  
