dataset_name: "YBCO13_fold10_paper"
train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold10_train"
validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold10_val"
test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold10_test"  
