dataset_name: "YBCO13_fold2"
train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold2_train"
validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold2_val"
test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold2_test"  
