dataset_name: "YBCO13_fold19_paper"
train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold19_train"
validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold19_val"
test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold19_test"  
