dataset_name: "YBCO13_fold6"
    train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold6_train"
    validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold6_val"
    test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold6_test"  
    