dataset_name: "YBCO13_fold18_paper"
train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold18_train"
validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold18_val"
test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold18_test"  
