dataset_name: "YBCO13_fold16_paper"
train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold16_train"
validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold16_val"
test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold16_test"  
