dataset_name: "YBCO13_fold17"
train_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold17_train"
validation_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold17_val"
test_dataset_dir: "/workspace/data/dataset_paper/dataset_YBCO13_fold17_test"  
